name: Publish VS Code Extension

on:
  workflow_run:
    workflows: ["Build VS Code Extension"]
    types:
      - completed
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'release' }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run compile

      - name: Download build artifact
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          name: extension-vsix
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Package VSIX (if not from artifact)
        if: github.event_name == 'release'
        run: npx vsce package

      - name: Publish to VS Code Marketplace
        run: npx vsce publish --no-dependencies
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX Registry
        run: npx ovsx publish --no-dependencies
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
